// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXFufzNF5CcfvbnOohR1COfBwYwAnSclY',
    appId: '1:877175644081:web:9a7a6f5dc52054bb792790',
    messagingSenderId: '877175644081',
    projectId: 'guchi-app-flutter',
    authDomain: 'guchi-app-flutter.firebaseapp.com',
    storageBucket: 'guchi-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvCEvEkag07TWevo72Oo7ufrGRcx_EcsA',
    appId: '1:877175644081:android:a568a09cdfecf7e7792790',
    messagingSenderId: '877175644081',
    projectId: 'guchi-app-flutter',
    storageBucket: 'guchi-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm2UXVnRsArZmVZoT2YOXw-Qf_Bf8H1Xw',
    appId: '1:877175644081:ios:13c10e43d6ce0085792790',
    messagingSenderId: '877175644081',
    projectId: 'guchi-app-flutter',
    storageBucket: 'guchi-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm2UXVnRsArZmVZoT2YOXw-Qf_Bf8H1Xw',
    appId: '1:877175644081:ios:13c10e43d6ce0085792790',
    messagingSenderId: '877175644081',
    projectId: 'guchi-app-flutter',
    storageBucket: 'guchi-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXFufzNF5CcfvbnOohR1COfBwYwAnSclY',
    appId: '1:877175644081:web:8059363106c94f6a792790',
    messagingSenderId: '877175644081',
    projectId: 'guchi-app-flutter',
    authDomain: 'guchi-app-flutter.firebaseapp.com',
    storageBucket: 'guchi-app-flutter.firebasestorage.app',
  );
}
