name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  # ------ CI (ビルドとテスト) ジョブ ------
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'master' # 'beta' を 'master' に変更

      - name: Install dependencies
        run: flutter pub get

      - name: Create .env file for build
        working-directory: frontend # 'frontend' ディレクトリで実行
        run: |
          echo "GOOGLE_WEB_CLIENT_ID=${{ secrets.GOOGLE_WEB_CLIENT_ID }}" > .env

      - name: Run analyzer
        run: flutter analyze

      # - name: Run tests
      #   run: flutter test

      - name: Build for Web
        run: flutter build web --release

      - name: Archive web build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: frontend/build/web

  # ------ CD (デプロイ) ジョブ ------
  deploy_to_hosting:
    name: Deploy to Firebase Hosting
    needs: build_and_test # build_and_testジョブの成功が必須
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Workload Identity連携に必要

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download web build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: frontend/build/web

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        working-directory: ./frontend
        run: firebase deploy --only hosting --project ${{ secrets.GCP_PROJECT_ID }} --non-interactive
