name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    # ★★★ 1. GCP認証のための権限を追加 ★★★
    permissions:
      contents: 'read'
      id-token: 'write'
    defaults:
      run:
        working-directory: frontend
    
    env:
      GOOGLE_WEB_CLIENT_ID: ${{ secrets.GOOGLE_WEB_CLIENT_ID }}
      # ★★★ 1. envセクションにRECAPTCHA_SITE_KEYを追加 ★★★
      RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ★★★ 2. GCPへの認証ステップを追加 ★★★
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # Flutterのバージョンを安定版に固定することを推奨します
          channel: 'stable'

      # ★★★ ここから追加 ★★★
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase Tools and FlutterFire CLI
        run: |
          npm install -g firebase-tools
          dart pub global activate flutterfire_cli
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
        # ★★★ ここまで追加 ★★★

      - name: Install dependencies
        run: flutter pub get

      # ★★★ firebase_options.dart を生成するステップ ★★★
      # 以前のファイルコピー(cp)は不要です
      - name: Configure Firebase
        run: flutterfire configure --project=${{ secrets.GCP_PROJECT_ID }} --yes --out=lib/firebase_options.dart --platforms=web

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests # ★★★ このステップを追加 ★★★
        run: flutter test

      - name: Build for Web
        # ★★★ 2. buildコマンドにRECAPTCHA_SITE_KEYの--dart-defineを追加 ★★★
        run: flutter build web --release --dart-define=GOOGLE_WEB_CLIENT_ID="${{ env.GOOGLE_WEB_CLIENT_ID }}" --dart-define=RECAPTCHA_SITE_KEY="${{ env.RECAPTCHA_SITE_KEY }}"

      - name: Archive web build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: frontend/build/web

  deploy_to_hosting:
    name: Deploy to Firebase Hosting
    needs: build_and_test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download web build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: frontend/build/web

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        working-directory: ./frontend
        run: firebase deploy --only hosting --project ${{ secrets.GCP_PROJECT_ID }} --non-interactive