name: Gateway CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'gateway/**'
      - '.github/workflows/gateway-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'gateway/**'
      - '.github/workflows/gateway-ci.yml'

# --- ワークフロー全体で使う環境変数を定義 ---
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  CLOUD_RUN_SERVICE_NAME: ${{ secrets.CLOUD_RUN_SERVICE_NAME }}
  ARTIFACT_REGISTRY_REPOSITORY: ${{ secrets.ARTIFACT_REGISTRY_REPOSITORY }}
  IMAGE_NAME: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPOSITORY }}/${{ secrets.CLOUD_RUN_SERVICE_NAME }}

jobs:
  gateway-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gateway
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Lint (flake8)
      run: |
        pip install flake8
        flake8 . --exclude=venv,.venv,__pycache__ --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Check if Flask app runs
      run: python -m py_compile main.py

deploy:
  needs: gateway-test
  if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  runs-on: ubuntu-latest
  permissions:
    contents: 'read'
    id-token: 'write'

  steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Authenticate to Google Cloud
    uses: 'google-github-actions/auth@v2'
    with:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

  - name: Set up Cloud SDK
    uses: 'google-github-actions/setup-gcloud@v2'

  - name: Configure Docker
    run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

  - name: Build and push Docker image
    env:
      IMAGE_TAG: ${{ github.sha }}
    run: |-
      docker build -t ${{ env.IMAGE_NAME }}:${IMAGE_TAG} -t ${{ env.IMAGE_NAME }}:latest ./gateway
      docker push ${{ env.IMAGE_NAME }}:${IMAGE_TAG}
      docker push ${{ env.IMAGE_NAME }}:latest

  - name: Deploy to Cloud Run
    env:
      IMAGE_TAG: ${{ github.sha }}
    run: |-
      gcloud run deploy ${{ env.CLOUD_RUN_SERVICE_NAME }} \
        --image ${{ env.IMAGE_NAME }}:${IMAGE_TAG} \
        --region ${{ env.GCP_REGION }} \
        --platform managed \
        --quiet \
        --allow-unauthenticated \
        --service-account=${{ secrets.GCP_SERVICE_ACCOUNT }}